name = "FoFC"
author = "Zebee"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e5cfafb50950e0df10ba98b096c2c0146f0690062eee81496b5b02c0183b5b9"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
