name = "FoFC"
author = "Zebee"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4f54de046d3008f86266c4ab71cd5110108c5e3d356d93e983b3ac69ce08d62"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
